1. Write a program to generate Arithmetic Exception without exception handling 
2. Handle the Arithmetic exception using try-catch block 
3. Write a method which throws exception, call that method in main class without try block 
4. Write a program with multiple catch blocks 
5. Write a program to throw exception with your own message 
6. Write a program to create your own exception 
7. Write a program with finally block 
8. Write a program to generate Arithmetic Exception 
9. Write a program to generate FileNotFoundException 
10. Write a program to generate ClassNotFoundException 
11. Write a program to generate IOException 
12. Write a program to generate NoSuchFieldException.

a = [1, 2, 3]
try:
    print ("Second element = ",a[1])
    print ("Fourth element = ",a[3])
    
except:
    print ("An error occurred")

print()

b = [3,2,1]
try:
    a == b
except:
    print("They are not equal")
else:
    print("Both Equal") 

print()

try:
    k = 5/0
    print(k)
except ZeroDivisionError:
    print("Can't divide by zero")
finally:
    print('This is always executed') 
